# -*- coding: utf-8 -*-
from calibration_oscil import Param_osc, Call_oscill, Supportfunc, Clear_merge

for j in range(1,3,1):
    # dcv
    Supportfunc(f'message-Подключите формирователь без вешней нагрузки на КАНАЛ №{j} осциллографа')
    Supportfunc('reset_ads')
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP DC', ':TIM:SCAL 500us', '')
    Call_oscill('VOLT 0.006', f':CHAN{j}:SCAL 2mv', ':MEAS:MAX?', f'dcv{j}+_1', f'gdcv{j}+_1', 3)
    Call_oscill('VOLT -0.006', f':CHAN{j}:SCAL 2mv', ':MEAS:MAX?', f'dcv{j}-_1', f'gdcv{j}-_1', 3)
    Call_oscill('VOLT 0.015', f':CHAN{j}:SCAL 5mv', ':MEAS:MAX?', f'dcv{j}+_2', f'gdcv{j}+_2', 3)
    Call_oscill('VOLT -0.015', f':CHAN{j}:SCAL 5mv', ':MEAS:MAX?', f'dcv{j}-_2', f'gdcv{j}-_2', 3)
    Call_oscill('VOLT 0.03', f':CHAN{j}:SCAL 10mv', ':MEAS:MAX?', f'dcv{j}+_3', f'gdcv{j}+_3', 3)
    Call_oscill('VOLT -0.03', f':CHAN{j}:SCAL 10mv', ':MEAS:MAX?', f'dcv{j}-_3', f'gdcv{j}-_3', 3)
    Call_oscill('VOLT 0.06', f':CHAN{j}:SCAL 20mv', ':MEAS:MAX?', f'dcv{j}+_4', f'gdcv{j}+_4', 3)
    Call_oscill('VOLT -0.06', f':CHAN{j}:SCAL 20mv', ':MEAS:MAX?', f'dcv{j}-_4', f'gdcv{j}-_4', 3)
    Call_oscill('VOLT 0.15', f':CHAN{j}:SCAL 50mv', ':MEAS:MAX?', f'dcv{j}+_5', f'gdcv{j}+_5', 3)
    Call_oscill('VOLT -0.15', f':CHAN{j}:SCAL 50mv', ':MEAS:MAX?', f'dcv{j}-_5', f'gdcv{j}-_5', 3)
    Call_oscill('VOLT 0.3', f':CHAN{j}:SCAL 100mv', ':MEAS:MAX?', f'dcv{j}+_6', f'gdcv{j}+_6', 3)
    Call_oscill('VOLT -0.3', f':CHAN{j}:SCAL 100mv', ':MEAS:MAX?', f'dcv{j}-_6', f'gdcv{j}-_6', 3)
    Call_oscill('VOLT 0.6', f':CHAN{j}:SCAL 200mv', ':MEAS:MAX?', f'dcv{j}+_7', f'gdcv{j}+_7', 3)
    Call_oscill('VOLT -0.6', f':CHAN{j}:SCAL 200mv', ':MEAS:MAX?', f'dcv{j}-_7', f'gdcv{j}-_7', 3)
    Call_oscill('VOLT 1.5', f':CHAN{j}:SCAL 500mv', ':MEAS:MAX?', f'dcv{j}+_8', f'gdcv{j}+_8', 3)
    Call_oscill('VOLT -1.5', f':CHAN{j}:SCAL 500mv', ':MEAS:MAX?', f'dcv{j}-_8', f'gdcv{j}-_8', 3)
    Call_oscill('VOLT 3', f':CHAN{j}:SCAL 1v', ':MEAS:MAX?', f'dcv{j}+_9', f'gdcv{j}+_9', 3)
    Call_oscill('VOLT -3', f':CHAN{j}:SCAL 1v', ':MEAS:MAX?', f'dcv{j}-_9', f'gdcv{j}-_9', 3)
    Call_oscill('VOLT 6', f':CHAN{j}:SCAL 2v', ':MEAS:MAX?', f'dcv{j}+_10', f'gdcv{j}+_10', 3)
    Call_oscill('VOLT -6', f':CHAN{j}:SCAL 2v', ':MEAS:MAX?', f'dcv{j}-_10', f'gdcv{j}-_10', 3)
    Call_oscill('VOLT 15', f':CHAN{j}:SCAL 5v', ':MEAS:MAX?', f'dcv{j}+_11', f'gdcv{j}+_11', 3)
    Call_oscill('VOLT -15', f':CHAN{j}:SCAL 5v', ':MEAS:MAX?', f'dcv{j}-_11', f'gdcv{j}-_11', 3)
    Call_oscill('VOLT 10', f':CHAN{j}:SCAL 10v', ':MEAS:MAX?', f'dcv{j}+_12', f'gdcv{j}+_12', 3)
    Call_oscill('VOLT -10', f':CHAN{j}:SCAL 10v', ':MEAS:MAX?', f'dcv{j}-_12', f'gdcv{j}-_12', 3)
    Call_oscill('VOLT 20', f':CHAN{j}:SCAL 10v', ':MEAS:MAX?', f'dcv{j}+_13', f'gdcv{j}+_13', 3)
    Call_oscill('VOLT -20', f':CHAN{j}:SCAL 10v', ':MEAS:MAX?', f'dcv{j}-_13', f'gdcv{j}-_13', 3)
    Call_oscill('VOLT 30', f':CHAN{j}:SCAL 10v', ':MEAS:MAX?', f'dcv{j}+_14', f'gdcv{j}+_14', 3)
    Call_oscill('VOLT -30', f':CHAN{j}:SCAL 10v', ':MEAS:MAX?', f'dcv{j}-_14', f'gdcv{j}-_14', 3)
    # period
    '''Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 5E-9', 'PER:FIX 5E-09')
    Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f'ti{j}_1', f'gti{j}_1', 0.61)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 50E-9', 'PER:FIX 100E-09')
    Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f'ti{j}_2', f'gti{j}_2', 0.81)'''
    # trise
    Supportfunc(f'message-Подключите внешнию нагрузку 50 Ом на КАНАЛ №{j} осциллографа')
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP EDGE', ':TIM:SCAL 5.0ns', ':TRIG:SING:EDGE:SLOP RISE')
    Call_oscill('VOLT 0.03', f':CHAN{j}:SCAL 5mv', ':MEAS:RTIM?', f'tr{j}_1', ':TRIG:SING:EDGE:LEV -30', 1.8)
    Call_oscill('VOLT 0.06', f':CHAN{j}:SCAL 10mv', ':MEAS:RTIM?', f'tr{j}_2', ':TRIG:SING:EDGE:LEV -30', 1.8)
    Call_oscill('VOLT 0.12', f':CHAN{j}:SCAL 20mv', ':MEAS:RTIM?', f'tr{j}_3', ':TRIG:SING:EDGE:LEV -30', 1.8)
    Call_oscill('VOLT 0.3', f':CHAN{j}:SCAL 50mv', ':MEAS:RTIM?', f'tr{j}_4', ':TRIG:SING:EDGE:LEV -30', 1.8)
    Call_oscill('VOLT 0.6', f':CHAN{j}:SCAL 100mv', ':MEAS:RTIM?', f'tr{j}_5', ':TRIG:SING:EDGE:LEV -30', 1.8)
    Call_oscill('VOLT 1.2', f':CHAN{j}:SCAL 200mv', ':MEAS:RTIM?', f'tr{j}_6', ':TRIG:SING:EDGE:LEV -30', 1.8)
    Call_oscill('VOLT 3.1', f':CHAN{j}:SCAL 500mv', ':MEAS:RTIM?', f'tr{j}_7', ':TRIG:SING:EDGE:LEV -15', 1.8)
    Call_oscill('VOLT 3.1', f':CHAN{j}:SCAL 1v', ':MEAS:RTIM?', f'tr{j}_8', ':TRIG:SING:EDGE:LEV -15', 1.8)
    Call_oscill('VOLT 3.1', f':CHAN{j}:SCAL 2v', ':MEAS:RTIM?', f'tr{j}_9', ':TRIG:SING:EDGE:LEV -15', 1.8)
    #Call_oscill('VOLT 3.1', f':CHAN{j}:SCAL 5v', ':MEAS:RTIM?', f'tr{j}_10', ':TRIG:SING:EDGE:LEV -10', 1.8)
    #Call_oscill('VOLT 3.1', f':CHAN{j}:SCAL 10v', ':MEAS:RTIM?', f'tr{j}_11', ':TRIG:SING:EDGE:LEV -2', 1.8)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP EDGE', ':TIM:SCAL 5.0ns', ':TRIG:SING:EDGE:SLOP FALL')
    Call_oscill('VOLT 0.03', f':CHAN{j}:SCAL 5mv', ':MEAS:RTIM?', f'tf{j}_1', ':TRIG:SING:EDGE:LEV 133', 1.8)
    Call_oscill('VOLT 0.06', f':CHAN{j}:SCAL 10mv', ':MEAS:RTIM?', f'tf{j}_2', ':TRIG:SING:EDGE:LEV 133', 1.8)
    Call_oscill('VOLT 0.12', f':CHAN{j}:SCAL 20mv', ':MEAS:RTIM?', f'tf{j}_3', ':TRIG:SING:EDGE:LEV 133', 1.8)
    Call_oscill('VOLT 0.3', f':CHAN{j}:SCAL 50mv', ':MEAS:RTIM?', f'tf{j}_4', ':TRIG:SING:EDGE:LEV 133', 1.8)
    Call_oscill('VOLT 0.6', f':CHAN{j}:SCAL 100mv', ':MEAS:RTIM?', f'tf{j}_5', ':TRIG:SING:EDGE:LEV 133', 1.8)
    Call_oscill('VOLT 1.2', f':CHAN{j}:SCAL 200mv', ':MEAS:RTIM?', f'tf{j}_6', ':TRIG:SING:EDGE:LEV 133', 1.8)
    Call_oscill('VOLT 3.1', f':CHAN{j}:SCAL 500mv', ':MEAS:RTIM?', f'tf{j}_7', ':TRIG:SING:EDGE:LEV 80', 1.8)
    Call_oscill('VOLT 3.1', f':CHAN{j}:SCAL 1v', ':MEAS:RTIM?', f'tf{j}_8', ':TRIG:SING:EDGE:LEV 9', 1.8)
    Call_oscill('VOLT 3.1', f':CHAN{j}:SCAL 2v', ':MEAS:RTIM?', f'tf{j}_9', ':TRIG:SING:EDGE:LEV 9', 1.8)
    #Call_oscill('VOLT 3.1', f':CHAN{j}:SCAL 5v', ':MEAS:RTIM?', f'tf{j}_10', ':TRIG:SING:EDGE:LEV 9', 1.8)
    #Call_oscill('VOLT 3.1', f':CHAN{j}:SCAL 10v', ':MEAS:RTIM?', f'tf{j}_11', ':TRIG:SING:EDGE:LEV 9', 1.8)

Supportfunc('message-Калибровка завершена')
Clear_merge()
Supportfunc('reset_ads')
