# -*- coding: utf-8 -*-
from calibration_oscil import Param_osc, Call_oscill, Supportfunc, Clear_merge

for j in range(1,5,1):
    # res
    Supportfunc(f'message-Подключите формирователь на КАНАЛ №{j} осциллографа')
    Supportfunc('resetoscil')
    Param_osc(f'{j}', '', 'CONF:RES', 'TIM:SCAL 100E-6', '')
    Call_oscill('ROUT:SIGN:IMP 1E+06', f'CHAN{j}:SCAL 0.05', 'READ?', f'r{j}_1', '', 10000)
    Call_oscill('ROUT:SIGN:IMP 1E+06', f'CHAN{j}:SCAL 0.2', 'READ?', f'r{j}_2', '', 10000)
    # dcv
    Supportfunc('resetoscil')
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP DC', 'TIM:SCAL 100E-6', '')
    Call_oscill('VOLT 0.003', f'CHAN{j}:SCAL 0.001', ':MEAS:ITEM? VMAX', f'dcv{j}+_1', f'gdcv{j}+_1', 4.2)
    Call_oscill('VOLT -0.003', f'CHAN{j}:SCAL 0.001', ':MEAS:ITEM? VMAX', f'dcv{j}-_1', f'gdcv{j}-_1', 4.2)
    Call_oscill('VOLT 0.006', f'CHAN{j}:SCAL 0.002', ':MEAS:ITEM? VMAX', f'dcv{j}+_2', f'gdcv{j}+_2', 7.2)
    Call_oscill('VOLT -0.006', f'CHAN{j}:SCAL 0.002', ':MEAS:ITEM? VMAX', f'dcv{j}-_2', f'gdcv{j}-_2', 7.2)
    Call_oscill('VOLT 0.015', f'CHAN{j}:SCAL 0.005', ':MEAS:ITEM? VMAX', f'dcv{j}+_3', f'gdcv{j}+_3', 16.2)
    Call_oscill('VOLT -0.015', f'CHAN{j}:SCAL 0.005', ':MEAS:ITEM? VMAX', f'dcv{j}-_3', f'gdcv{j}-_3', 16.2)
    Call_oscill('VOLT 0.03', f'CHAN{j}:SCAL 0.01', ':MEAS:ITEM? VMAX', f'dcv{j}+_4', f'gdcv{j}+_4', 33)
    Call_oscill('VOLT -0.03', f'CHAN{j}:SCAL 0.01', ':MEAS:ITEM? VMAX', f'dcv{j}-_4', f'gdcv{j}-_4', 33)
    Call_oscill('VOLT 0.06', f'CHAN{j}:SCAL 0.02', ':MEAS:ITEM? VMAX', f'dcv{j}+_5', f'gdcv{j}+_5', 66)
    Call_oscill('VOLT -0.06', f'CHAN{j}:SCAL 0.02', ':MEAS:ITEM? VMAX', f'dcv{j}-_5', f'gdcv{j}-_5', 66)
    Call_oscill('VOLT 0.15', f'CHAN{j}:SCAL 0.05', ':MEAS:ITEM? VMAX', f'dcv{j}+_6', f'gdcv{j}+_6', 165)
    Call_oscill('VOLT -0.15', f'CHAN{j}:SCAL 0.05', ':MEAS:ITEM? VMAX', f'dcv{j}-_6', f'gdcv{j}-_6', 165)
    Call_oscill('VOLT 0.3', f'CHAN{j}:SCAL 0.1', ':MEAS:ITEM? VMAX', f'dcv{j}+_7', f'gdcv{j}+_7', 330)
    Call_oscill('VOLT -0.3', f'CHAN{j}:SCAL 0.1', ':MEAS:ITEM? VMAX', f'dcv{j}-_7', f'gdcv{j}-_7', 330)
    Call_oscill('VOLT 0.6', f'CHAN{j}:SCAL 0.2', ':MEAS:ITEM? VMAX', f'dcv{j}+_8', f'gdcv{j}+_8', 660)
    Call_oscill('VOLT -0.6', f'CHAN{j}:SCAL 0.2', ':MEAS:ITEM? VMAX', f'dcv{j}-_8', f'gdcv{j}-_8', 660)
    Call_oscill('VOLT 1.5', f'CHAN{j}:SCAL 0.5', ':MEAS:ITEM? VMAX', f'dcv{j}+_9', f'gdcv{j}+_9', 1.65)
    Call_oscill('VOLT -1.5', f'CHAN{j}:SCAL 0.5', ':MEAS:ITEM? VMAX', f'dcv{j}-_9', f'gdcv{j}-_9', 1.65)
    Call_oscill('VOLT 3', f'CHAN{j}:SCAL 1', ':MEAS:ITEM? VMAX', f'dcv{j}+_10', f'gdcv{j}+_10', 3.3)
    Call_oscill('VOLT -3', f'CHAN{j}:SCAL 1', ':MEAS:ITEM? VMAX', f'dcv{j}-_10', f'gdcv{j}-_10', 3.3)
    Call_oscill('VOLT 6', f'CHAN{j}:SCAL 2', ':MEAS:ITEM? VMAX', f'dcv{j}+_11', f'gdcv{j}+_11', 6.6)
    Call_oscill('VOLT -6', f'CHAN{j}:SCAL 2', ':MEAS:ITEM? VMAX', f'dcv{j}-_11', f'gdcv{j}-_11', 6.6)
    Call_oscill('VOLT 15', f'CHAN{j}:SCAL 5', ':MEAS:ITEM? VMAX', f'dcv{j}+_12', f'gdcv{j}+_12', 16.5)
    Call_oscill('VOLT -15', f'CHAN{j}:SCAL 5', ':MEAS:ITEM? VMAX', f'dcv{j}-_12', f'gdcv{j}-_12', 16.5)
    Call_oscill('VOLT 30', f'CHAN{j}:SCAL 10', ':MEAS:ITEM? VMAX', f'dcv{j}+_13', f'gdcv{j}+_13', 33)
    Call_oscill('VOLT -30', f'CHAN{j}:SCAL 10', ':MEAS:ITEM? VMAX', f'dcv{j}-_13', f'gdcv{j}-_13', 33)
    # offset
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP DC', 'TIM:SCAL 100E-6', '')
    Call_oscill('VOLT -1', f'CHAN{j}:SCAL 0.01', '1', f'vofs{j}-_1', f'gvofs{j}-_1', 1.018)
    Call_oscill('VOLT 1', f'CHAN{j}:SCAL 0.01', '-1', f'vofs{j}+_1', f'gvofs{j}+_1', 1.018)
    Call_oscill('VOLT -10', f'CHAN{j}:SCAL 0.1', '10', f'vofs{j}-_2', f'gvofs{j}-_2', 10.162)
    Call_oscill('VOLT 10', f'CHAN{j}:SCAL 0.1', '-10', f'vofs{j}+_2', f'gvofs{j}+_2', 10.162)
    Call_oscill('VOLT -30', f'CHAN{j}:SCAL 0.2', '30', f'vofs{j}-_3', f'gvofs{j}-_3', 30.472)
    Call_oscill('VOLT 30', f'CHAN{j}:SCAL 0.2', '-30', f'vofs{j}+_3', f'gvofs{j}+_3', 30.472)
    Call_oscill('VOLT -40', f'CHAN{j}:SCAL 0.5', '40', f'vofs{j}-_4', f'gvofs{j}-_4', 40.452)
    Call_oscill('VOLT 40', f'CHAN{j}:SCAL 0.5', '-40', f'vofs{j}+_4', f'gvofs{j}+_4', 40.452)
    Call_oscill('VOLT -50', f'CHAN{j}:SCAL 1', '50', f'vofs{j}-_5', f'gvofs{j}-_5', 50.602)
    Call_oscill('VOLT 50', f'CHAN{j}:SCAL 1', '-50', f'vofs{j}+_5', f'gvofs{j}+_5', 50.602)
    Call_oscill('VOLT -100', f'CHAN{j}:SCAL 10', '100', f'vofs{j}-_6', f'gvofs{j}-_6', 102.002)
    Call_oscill('VOLT 100', f'CHAN{j}:SCAL 10', '-100', f'vofs{j}+_6', f'gvofs{j}+_6', 102.002)
    # band
    Supportfunc('resetoscil')
    Supportfunc(f'message-Подключите внешнию нагрузку 50 Ом на КАНАЛ №{j} осциллографа')
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 50E+03', 'TIM:SCAL 10E-6', '')
    Call_oscill('VOLT 0.01', f'CHAN{j}:SCAL 0.002', ':MEAS:ITEM? VTOP', f'bw{j}_50_1', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 200E+06', 'TIM:SCAL 5E-9', '')
    Call_oscill('VOLT 0.01', f'CHAN{j}:SCAL 0.002', ':MEAS:ITEM? VTOP', f'bw{j}_200_1', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 50E+03', 'TIM:SCAL 10E-6', '')
    Call_oscill('VOLT 0.03', f'CHAN{j}:SCAL 0.005', ':MEAS:ITEM? VTOP', f'bw{j}_50_2', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 200E+06', 'TIM:SCAL 5E-9', '')
    Call_oscill('VOLT 0.03', f'CHAN{j}:SCAL 0.005', ':MEAS:ITEM? VTOP', f'bw{j}_200_2', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 50E+03', 'TIM:SCAL 10E-6', '')
    Call_oscill('VOLT 0.06', f'CHAN{j}:SCAL 0.01', ':MEAS:ITEM? VTOP', f'bw{j}_50_3', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 200E+06', 'TIM:SCAL 5E-9', '')
    Call_oscill('VOLT 0.06', f'CHAN{j}:SCAL 0.01', ':MEAS:ITEM? VTOP', f'bw{j}_200_3', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 50E+03', 'TIM:SCAL 10E-6', '')
    Call_oscill('VOLT 0.12', f'CHAN{j}:SCAL 0.02', ':MEAS:ITEM? VTOP', f'bw{j}_50_4', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 200E+06', 'TIM:SCAL 5E-9', '')
    Call_oscill('VOLT 0.12', f'CHAN{j}:SCAL 0.02', ':MEAS:ITEM? VTOP', f'bw{j}_200_4', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 50E+03', 'TIM:SCAL 10E-6', '')
    Call_oscill('VOLT 0.3', f'CHAN{j}:SCAL 0.05', ':MEAS:ITEM? VTOP', f'bw{j}_50_5', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 200E+06', 'TIM:SCAL 5E-9', '')
    Call_oscill('VOLT 0.3', f'CHAN{j}:SCAL 0.05', ':MEAS:ITEM? VTOP', f'bw{j}_200_5', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 50E+03', 'TIM:SCAL 10E-6', '')
    Call_oscill('VOLT 0.6', f'CHAN{j}:SCAL 0.1', ':MEAS:ITEM? VTOP', f'bw{j}_50_6', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 200E+06', 'TIM:SCAL 5E-9', '')
    Call_oscill('VOLT 0.6', f'CHAN{j}:SCAL 0.1', ':MEAS:ITEM? VTOP', f'bw{j}_200_6', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 50E+03', 'TIM:SCAL 10E-6', '')
    Call_oscill('VOLT 1.2', f'CHAN{j}:SCAL 0.2', ':MEAS:ITEM? VTOP', f'bw{j}_50_7', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 200E+06', 'TIM:SCAL 5E-9', '')
    Call_oscill('VOLT 1.2', f'CHAN{j}:SCAL 0.2', ':MEAS:ITEM? VTOP', f'bw{j}_200_7', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 50E+03', 'TIM:SCAL 10E-6', '')
    Call_oscill('VOLT 3', f'CHAN{j}:SCAL 0.5', ':MEAS:ITEM? VTOP', f'bw{j}_50_8', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 200E+06', 'TIM:SCAL 5E-9', '')
    Call_oscill('VOLT 3', f'CHAN{j}:SCAL 0.5', ':MEAS:ITEM? VTOP', f'bw{j}_200_8', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 50E+03', 'TIM:SCAL 10E-6', '')
    Call_oscill('VOLT 5.5', f'CHAN{j}:SCAL 1', ':MEAS:ITEM? VTOP', f'bw{j}_50_9', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 200E+06', 'TIM:SCAL 5E-9', '')
    Call_oscill('VOLT 5.5', f'CHAN{j}:SCAL 1', ':MEAS:ITEM? VTOP', f'bw{j}_200_9', '', 3)

Supportfunc('message-Калибровка завершена')
Clear_merge()
Supportfunc('resetoscil')
