# -*- coding: utf-8 -*-
for j in range(1,3,1):
    # dcv
    Supportfunc(f'message-Подключите формирователь без нагрузки на КАНАЛ №{j} осциллографа')
    Supportfunc('resetoscil')
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP DC', 'TIM:SCAL 100E-6', '')
    Call_oscill('VOLT 0.003', f'CHAN{j}:SCAL 0.001', ':MEAS:VAV?', f'dcv{j}+_1', f'gdcv{j}+_1', 0.32)
    Call_oscill('VOLT -0.003', f'CHAN{j}:SCAL 0.001', ':MEAS:VAV?', f'dcv{j}-_1', f'gdcv{j}-_1', 0.32)
    Call_oscill('VOLT 0.006', f'CHAN{j}:SCAL 0.002', ':MEAS:VAV?', f'dcv{j}+_2', f'gdcv{j}+_2', 0.32)
    Call_oscill('VOLT -0.006', f'CHAN{j}:SCAL 0.002', ':MEAS:VAV?', f'dcv{j}-_2', f'gdcv{j}-_2', 0.32)
    Call_oscill('VOLT 0.015', f'CHAN{j}:SCAL 0.005', ':MEAS:VAV?', f'dcv{j}+_3', f'gdcv{j}+_3', 0.8)
    Call_oscill('VOLT -0.015', f'CHAN{j}:SCAL 0.005', ':MEAS:VAV?', f'dcv{j}-_3', f'gdcv{j}-_3', 0.8)
    Call_oscill('VOLT 0.03', f'CHAN{j}:SCAL 0.01', ':MEAS:VAV?', f'dcv{j}+_4', f'gdcv{j}+_4', 1.6)
    Call_oscill('VOLT -0.03', f'CHAN{j}:SCAL 0.01', ':MEAS:VAV?', f'dcv{j}-_4', f'gdcv{j}-_4', 1.6)
    Call_oscill('VOLT 0.06', f'CHAN{j}:SCAL 0.02', ':MEAS:VAV?', f'dcv{j}+_5', f'gdcv{j}+_5', 3.2)
    Call_oscill('VOLT -0.06', f'CHAN{j}:SCAL 0.02', ':MEAS:VAV?', f'dcv{j}-_5', f'gdcv{j}-_5', 3.2)
    Call_oscill('VOLT 0.15', f'CHAN{j}:SCAL 0.05', ':MEAS:VAV?', f'dcv{j}+_6', f'gdcv{j}+_6', 8)
    Call_oscill('VOLT -0.15', f'CHAN{j}:SCAL 0.05', ':MEAS:VAV?', f'dcv{j}-_6', f'gdcv{j}-_6', 8)
    Call_oscill('VOLT 0.3', f'CHAN{j}:SCAL 0.1', ':MEAS:VAV?', f'dcv{j}+_7', f'gdcv{j}+_7', 16)
    Call_oscill('VOLT -0.3', f'CHAN{j}:SCAL 0.1', ':MEAS:VAV?', f'dcv{j}-_7', f'gdcv{j}-_7', 16)
    Call_oscill('VOLT 0.6', f'CHAN{j}:SCAL 0.2', ':MEAS:VAV?', f'dcv{j}+_8', f'gdcv{j}+_8', 32)
    Call_oscill('VOLT -0.6', f'CHAN{j}:SCAL 0.2', ':MEAS:VAV?', f'dcv{j}-_8', f'gdcv{j}-_8', 32)
    Call_oscill('VOLT 1.5', f'CHAN{j}:SCAL 0.5', ':MEAS:VAV?', f'dcv{j}+_9', f'gdcv{j}+_9', 80)
    Call_oscill('VOLT -1.5', f'CHAN{j}:SCAL 0.5', ':MEAS:VAV?', f'dcv{j}-_9', f'gdcv{j}-_9', 80)
    Call_oscill('VOLT 3', f'CHAN{j}:SCAL 1', ':MEAS:VAV?', f'dcv{j}+_10', f'gdcv{j}+_10', 160)
    Call_oscill('VOLT -3', f'CHAN{j}:SCAL 1', ':MEAS:VAV?', f'dcv{j}-_10', f'gdcv{j}-_10', 160)
    Call_oscill('VOLT 6', f'CHAN{j}:SCAL 2', ':MEAS:VAV?', f'dcv{j}+_11', f'gdcv{j}+_11', 320)
    Call_oscill('VOLT -6', f'CHAN{j}:SCAL 2', ':MEAS:VAV?', f'dcv{j}-_11', f'gdcv{j}-_11', 320)
    Call_oscill('VOLT 5', f'CHAN{j}:SCAL 5', ':MEAS:VAV?', f'dcv{j}+_12', f'gdcv{j}+_12', 800)
    Call_oscill('VOLT -5', f'CHAN{j}:SCAL 5', ':MEAS:VAV?', f'dcv{j}-_12', f'gdcv{j}-_12', 800)
    Call_oscill('VOLT 10', f'CHAN{j}:SCAL 5', ':MEAS:VAV?', f'dcv{j}+_13', f'gdcv{j}+_13', 800)
    Call_oscill('VOLT -10', f'CHAN{j}:SCAL 5', ':MEAS:VAV?', f'dcv{j}-_13', f'gdcv{j}-_13', 800)
    Call_oscill('VOLT 15', f'CHAN{j}:SCAL 5', ':MEAS:VAV?', f'dcv{j}+_14', f'gdcv{j}+_14', 800)
    Call_oscill('VOLT -15', f'CHAN{j}:SCAL 5', ':MEAS:VAV?', f'dcv{j}-_14', f'gdcv{j}-_14', 800)
    Call_oscill('VOLT 20', f'CHAN{j}:SCAL 5', ':MEAS:VAV?', f'dcv{j}+_15', f'gdcv{j}+_15', 800)
    Call_oscill('VOLT -20', f'CHAN{j}:SCAL 5', ':MEAS:VAV?', f'dcv{j}-_15', f'gdcv{j}-_15', 800)
    # offset
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP DC', 'TIM:SCAL 100E-6', '')
    Call_oscill('VOLT -5', f'CHAN{j}:SCAL 0.002', '-5', f'vofs{j}-_1', f'gvofs{j}-_1', 27.2)
    Call_oscill('VOLT 5', f'CHAN{j}:SCAL 0.002', '5', f'vofs{j}+_1', f'gvofs{j}+_1', 27.2)
    Call_oscill('VOLT -5', f'CHAN{j}:SCAL 0.005', '-5', f'vofs{j}-_2', f'gvofs{j}-_2', 27.2)
    Call_oscill('VOLT 5', f'CHAN{j}:SCAL 0.005', '5', f'vofs{j}+_2', f'gvofs{j}+_2', 27.2)
    Call_oscill('VOLT -20', f'CHAN{j}:SCAL 0.01', '-20', f'vofs{j}-_3', f'gvofs{j}-_3', 103)
    Call_oscill('VOLT 20', f'CHAN{j}:SCAL 0.01', '20', f'vofs{j}+_3', f'gvofs{j}+_3', 103)
    Call_oscill('VOLT -20', f'CHAN{j}:SCAL 0.2', '-20', f'vofs{j}-_4', f'gvofs{j}-_4', 122)
    Call_oscill('VOLT 20', f'CHAN{j}:SCAL 0.2', '20', f'vofs{j}+_4', f'gvofs{j}+_4', 122)
    Call_oscill('VOLT -75', f'CHAN{j}:SCAL 0.5', '-75', f'vofs{j}-_5', f'gvofs{j}-_5', 1177)
    Call_oscill('VOLT 75', f'CHAN{j}:SCAL 0.5', '75', f'vofs{j}+_5', f'gvofs{j}+_5', 1177)
    Call_oscill('VOLT -75', f'CHAN{j}:SCAL 5', '-75', f'vofs{j}-_6', f'gvofs{j}-_6', 1627)
    Call_oscill('VOLT 75', f'CHAN{j}:SCAL 5', '75', f'vofs{j}+_6', f'gvofs{j}+_6', 1627)
    # trise
    Supportfunc(f'message-Подключите внешнию нагрузку 50 Ом на КАНАЛ №{j} осциллографа')
    Supportfunc('resetoscil')
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP EDGE', 'TIM:SCAL 0.5E-9', '')
    Call_oscill('VOLT 0.25', f'CHAN{j}:SCAL 0.05', ':MEAS:RIS?', f'tr_{j}', '', 3.5)
    # band
    Supportfunc('resetoscil')
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 1E+06', 'TIM:SCAL 500E-9', 'band')
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 1E+06', 'TIM:SCAL 500E-9', '')
    Call_oscill('VOLT 1.2', f'CHAN{j}:SCAL 0.2', ':MEAS:VRMS?', f'pdb{j}_1', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 10E+06', 'TIM:SCAL 50E-9', '')
    Call_oscill('VOLT 1.2', f'CHAN{j}:SCAL 0.2', ':MEAS:VRMS?', f'pdb{j}_2', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 20E+06', 'TIM:SCAL 20E-9', '')
    Call_oscill('VOLT 1.2', f'CHAN{j}:SCAL 0.2', ':MEAS:VRMS?', f'pdb{j}_3', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 30E+06', 'TIM:SCAL 20E-9', '')
    Call_oscill('VOLT 1.2', f'CHAN{j}:SCAL 0.2', ':MEAS:VRMS?', f'pdb{j}_4', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 50E+06', 'TIM:SCAL 10E-9', '')
    Call_oscill('VOLT 1.2', f'CHAN{j}:SCAL 0.2', ':MEAS:VRMS?', f'pdb{j}_5', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 80E+06', 'TIM:SCAL 5E-9', '')
    Call_oscill('VOLT 1.2', f'CHAN{j}:SCAL 0.2', ':MEAS:VRMS?', f'pdb{j}_6', '', 3)
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP SIN;, FREQ:FIX 100E+06', 'TIM:SCAL 5E-9', '')
    Call_oscill('VOLT 1.2', f'CHAN{j}:SCAL 0.2', ':MEAS:VRMS?', f'pdb{j}_7', '', 3)

Supportfunc('message-Калибровка завершена')
Clear_merge()
Supportfunc('resetoscil')
