# -*- coding: utf-8 -*-
from calibration_oscil import Param_osc, Call_oscill, Supportfunc, Clear_merge

for j in range(1,3,1):
    # dcv
    Supportfunc(f'message-Подключите формирователь без вешней нагрузки на КАНАЛ №{j} осциллографа')
    Supportfunc('resetoscil')
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP DC', 'HOR:SEC 500E-6', '')
    Call_oscill('VOLT 0.006', f'CH{j}:VOL 0.002', 'MEASU:MEAS1:VAL?', f'dcv{j}_1', f'gdcv{j}_1', 4)
    Call_oscill('VOLT 0.015', f'CH{j}:VOL 0.005', 'MEASU:MEAS1:VAL?', f'dcv{j}_2', f'gdcv{j}_2', 3)
    Call_oscill('VOLT 0.03', f'CH{j}:VOL 0.01', 'MEASU:MEAS1:VAL?', f'dcv{j}_3', f'gdcv{j}_3', 3)
    Call_oscill('VOLT 0.06', f'CH{j}:VOL 0.02', 'MEASU:MEAS1:VAL?', f'dcv{j}_4', f'gdcv{j}_4', 3)
    Call_oscill('VOLT 0.15', f'CH{j}:VOL 0.05', 'MEASU:MEAS1:VAL?', f'dcv{j}_5', f'gdcv{j}_5', 3)
    Call_oscill('VOLT 0.3', f'CH{j}:VOL 0.1', 'MEASU:MEAS1:VAL?', f'dcv{j}_6', f'gdcv{j}_6', 3)
    Call_oscill('VOLT 0.6', f'CH{j}:VOL 0.2', 'MEASU:MEAS1:VAL?', f'dcv{j}_7', f'gdcv{j}_7', 3)
    Call_oscill('VOLT 1.5', f'CH{j}:VOL 0.5', 'MEASU:MEAS1:VAL?', f'dcv{j}_8', f'gdcv{j}_8', 3)
    Call_oscill('VOLT 3', f'CH{j}:VOL 1', 'MEASU:MEAS1:VAL?', f'dcv{j}_9', f'gdcv{j}_9', 3)
    Call_oscill('VOLT 6', f'CH{j}:VOL 2', 'MEASU:MEAS1:VAL?', f'dcv{j}_10', f'gdcv{j}_10', 3)
    Call_oscill('VOLT 15', f'CH{j}:VOL 5', 'MEASU:MEAS1:VAL?', f'dcv{j}_11', f'gdcv{j}_11', 3)
    # period
    if j == 1:
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 10E-9', 'PER:FIX 10E-09')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_2', '', 0.001)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 25E-9', 'PER:FIX 25E-09')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_3', '', 0.0025)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 50E-9', 'PER:FIX 50E-09')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_4', '', 0.005)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 100E-9', 'PER:FIX 100E-9')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_5', '', 0.01)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 250E-9', 'PER:FIX 250E-9')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_6', '', 0.025)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 500E-9', 'PER:FIX 500E-9')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_7', '', 0.05)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 1E-6', 'PER:FIX 1E-6')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_8', '', 0.05)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 2.5E-6', 'PER:FIX 2.5E-6')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_9', '', 0.05)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 5E-6', 'PER:FIX 5E-6')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_10', '', 0.05)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 10E-6', 'PER:FIX 10E-6')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_11', '', 0.05)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 25E-6', 'PER:FIX 25E-6')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_12', '', 0.05)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 50E-6', 'PER:FIX 50E-6')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_13', '', 0.05)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 100E-6', 'PER:FIX 100E-6')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_14', '', 0.05)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 250E-6', 'PER:FIX 250E-6')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_15', '', 0.05)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 500E-6', 'PER:FIX 500E-6')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_16', '', 0.05)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 1E-3', 'PER:FIX 1E-3')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_17', '', 0.05)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 2.5E-3', 'PER:FIX 2.5E-3')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_18', '', 0.05)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 5E-3', 'PER:FIX 5E-3')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_19', '', 0.05)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 10E-3', 'PER:FIX 10E-3')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_20', '', 0.05)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 25E-3', 'PER:FIX 25E-3')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_21', '', 0.05)
        Param_osc(f'{j}', 'ROUT:SIGN:IMP 1E+06', 'SCOP:SHAP MARK', 'HOR:SEC 50E-3', 'PER:FIX 50E-3')
        Call_oscill('VOLT 1', f'CH{j}:VOL 0.2', 'MEASU:MEAS3:VAL?', f't{j}_22', '', 0.05)
    # trise
    # отсутствует выбор измерения времени нарастания
    '''Supportfunc(f'message-Подключите внешнию нагрузку 50 Ом на КАНАЛ №{j} осциллографа')
    Param_osc(f'{j}', 'ROUT:SIGN:IMP 50', 'SCOP:SHAP EDGE', 'HOR:SEC 5E-9', '')
    Call_oscill('VOLT 3.1', f'CH{j}:VOL 5\nTRIG:MAI:LEV -2', 'MEASU:MEAS4:VAL?', f'tr{j}_3', '', 3.5)
    Call_oscill('VOLT 3.1', f'CH{j}:VOL 1\nTRIG:MAI:LEV -1.5', 'MEASU:MEAS4:VAL?', f'tr{j}_2', '', 3.5)
    Call_oscill('VOLT 0.3', f'CH{j}:VOL 0.05\nTRIG:MAI:LEV -0.05', 'MEASU:MEAS4:VAL?', f'tr{j}_1', '', 3.5)'''

Supportfunc('message-Калибровка завершена')
Clear_merge()
Supportfunc('resetoscil')
